package net.bitzoo.rosalind

object FindAMotif {

  def main(args: Array[String]): Unit = {
    val bigString = "ACGTACGTACGTACGT"
    val smallString = "GTA"
    val bigString2 = "CCCGAACACTCTCTCACTCTCAGCACTCTCCAACACTCTCGACCACTCTCGCACTCTCACACTCTCCACTCTCTCCACTCTCGGGTGTGTTCACTCTCCACTCTCCACTCTCCACAACCACTCTCTCCACTCTCCACTCTCGTCACTCTCTGTGCACTCTCCCTCGTCGTCACTCTCGCCACTCTCAGCATCCACTCTCGTCACTCTCTTCCGCAAAACACTCTCACACTCTCATCACTCTCAACGTTCACTCTCCACTCTCACATCGCACTCTCACACTCTCACCACTCTCACACTCTCCACTCTCGCTCACTCTCTCACTCTCACTCACTCTCTAAGATTGTGTCTCAATCACTCTCGCACTCTCTCACTCTCCCACTCTCACACTCTCGGCTCCGCACTCTCGTATGACACTCTCCACTCTCTCCCCACTCTCTACACTCTCCTGTACAACACACTCTCGTTCACTCTCTTTCACTCTCATTACACTCTCTGCACTCTCGGGATTCACTCTCTACCCACTCTCCACTCTCCATCACTCTCCGGCCGTCTTCACTCTCCGCACTCTCTTCCACTCTCCAACAAGCCCCACTCTCTGCCAGCTAGCTCACTCTCCACTCTCGAGCCATACACTCTCCACTCTCCCACTCTCCTATACACTCTCCCACTCTCCACTCTCCACTCTCCACTCTCACACTCTCCCACTCTCTCTGCACTCTCCCACTCTCCGACACTCTCGTCACTCTCCGGAAACACTCTCCACTCTCTAGGTTTTTCACTCTCGTCACTCTCACACTCTCGCACTCTCCACTCTCTAGACACTCTCCACTCTCTTCCTAGCTCACGTATCACTCTCTGACACTCTCTGCACTCTCTACACTCTCTGGTCACTCTCCACTCTCCCTACACTCTC"
    val smallString2 = "CACTCTCCA"
    var idx = 0
    var indices = List[Int]()

    while (idx < bigString2.length() && idx != -1) {
      val loc = bigString2.indexOfSlice(smallString2, idx)
      if (loc != -1) {
        indices = loc + 1 :: indices
        idx = loc + 1
      } else idx = loc
    }

    Console.println(indices.reverse.mkString(" "))

  }

}